In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False  
pd.options.display.float_format = '{:.3f}'.format

In [2]:
os.mkdir('./data/typhoon')

# 황사

In [47]:
os.chdir('./data/황사')
os.getcwd()

'C:\\Users\\samsung\\Desktop\\DL_team\\data\\황사'

In [100]:
황사리스트 = os.listdir()
황사리스트 = list(set(황사리스트)-set([file for file in 황사리스트 if ('SNDE' in file) or ('WSPF' in file)]))

In [ ]:
df.columns

In [106]:
use_cols = ['일자', '지점명', '황사관측']
df = pd.read_csv(황사리스트[0], encoding='CP949')
df.columns = ['일자', '지점번호', '지점명', '황사관측', '평균 미세먼지 농도(㎍/㎥)', '평균 풍속(m/s)',
       '최대 풍속(m/s)', '최대 풍속 풍향(16방위)', '최다풍향(16방위)', '기사', '최단시정(10m)',
       '대기확산지수:+03시간', '+06시간', '+09시간', '+12시간', '+15시간', '+18시간', '+21시간',
       '+24시간']
df = df[use_cols]
for file_path1 in 황사리스트[1:]:
    df2 = pd.read_csv(file_path1, encoding='CP949')
    df2.columns = ['일자', '지점번호', '지점명', '황사관측', '평균 미세먼지 농도(㎍/㎥)', '평균 풍속(m/s)',
       '최대 풍속(m/s)', '최대 풍속 풍향(16방위)', '최다풍향(16방위)', '기사', '최단시정(10m)',
       '대기확산지수:+03시간', '+06시간', '+09시간', '+12시간', '+15시간', '+18시간', '+21시간',
       '+24시간']
    df2 =df2[use_cols]
    if df.columns.equals(df2.columns)==True: 
        df = pd.concat([df,df2], axis=0)
        #print(df.shape)
    else : 
        print('실패')
        print(df.columns)
        print(df2.columns)

In [110]:
df2 = df[df['지점명'].str.contains('서울')]

In [115]:
df2.sort_values(by='일자').drop_duplicates().reset_index(drop=True).to_csv('황사.csv', index=False)

# 태풍

In [123]:
df = pd.read_csv('태풍202101_202312.csv', encoding='CP949')
df.head()

   태풍명 진행여부 영향도                발생                소멸
0  두쥐안   종료  없음  2021.02.18 15:00  2021.02.22 09:00
1  수리개   종료  없음  2021.04.14 03:00  2021.04.25 09:00
2  초이완   종료  없음  2021.05.31 09:00  2021.06.03 09:00
3  고구마   종료  없음  2021.06.12 15:00  2021.06.13 15:00
4   참피   종료  없음  2021.06.23 09:00  2021.06.27 21:00

In [127]:
df['발생'] = pd.to_datetime(df['발생'].str[:10], format='%Y.%m.%d')
df['소멸'] = pd.to_datetime(df['소멸'].str[:10], format='%Y.%m.%d')
df.head()

   태풍명 진행여부 영향도         발생         소멸
0  두쥐안   종료  없음 2021-02-18 2021-02-22
1  수리개   종료  없음 2021-04-14 2021-04-25
2  초이완   종료  없음 2021-05-31 2021-06-03
3  고구마   종료  없음 2021-06-12 2021-06-13
4   참피   종료  없음 2021-06-23 2021-06-27

In [151]:
merged['태풍여부'] = merged.fillna('0')['태풍여부'].astype(int)
merged.head()

          날짜  태풍여부
0 2021-02-18     1
1 2021-02-19     1
2 2021-02-20     1
3 2021-02-21     1
4 2021-02-22     1

In [153]:
merged.to_csv('태풍.csv', index=False)